name: ecommerce_int2
description: It is about a complete ecommerce app for Android and iOS. 

version: 1.0.1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.1.2
  flutter_staggered_grid_view: ^0.3.0
  rubber: ^0.3.2
  pin_code_text_field: ^1.6.0
  country_code_picker: ^1.1.5
  http: any
  flutter_rating_bar: ^1.3.0+1
  intl: any
  numberpicker: ^1.0.0
  flare_splash_screen: ^2.1.2
  flutter_svg: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2+1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/shopeLogo.png"

flutter:
  uses-material-design: true

  assets:
  - assets/
  - assets/icons/

  fonts:
  - family: Montserrat
    fonts:
    - asset: fonts/Montserrat-Regular.ttf
  - family: NunitoSans
    fonts:
    - asset: fonts/NunitoSans-Regular.ttf

